DROP TABLE CAMPANIAS;
CREATE TABLE CAMPANIAS(
    ID_CAMP      NUMBER,
    NOMBRE_CAMP  VARCHAR2(20),
    DESCRIPCION  VARCHAR2(50),
    CONSTRAINT PK_CAMPANIAS PRIMARY KEY (ID_CAMP)
);

DROP TABLE AGRICULTORES;
CREATE TABLE AGRICULTORES(
    ID_AGRI      NUMBER,
    NOMBRE_AGRI  VARCHAR2(20),
    TELEFONO     NUMBER(9),
    ID_CAMP      NUMBER,
    CONSTRAINT PK_AGRICULTORES PRIMARY KEY (ID_AGRI)
);

DROP TABLE TRABAJOS;
CREATE TABLE TRABAJOS(
    ID_TRAB      NUMBER,
    NOMBRE_TRAB  VARCHAR2(20),
    MAQUINA      VARCHAR2(20),
    ID_AGRI      NUMBER,
    CONSTRAINT PK_TRABAJOS PRIMARY KEY (ID_TRAB)
);

ALTER TABLE AGRICULTORES ADD CONSTRAINT FK_AGRI_CAMP FOREIGN KEY (ID_CAMP) REFERENCES CAMPANIAS(ID_CAMP);
ALTER TABLE TRABAJOS ADD CONSTRAINT FK_TRAB_AGRI FOREIGN KEY (ID_AGRI) REFERENCES AGRICULTORES(ID_AGRI);